version: '3'
services:
  http:
    build: ./httpserver
    ports:
      - "3000:3000"
    environment:
      - JAEGER_HOST_NAME=jaeger
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - reselnet
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - reselnet
networks:
  reselnet: